### ISSUE TITLE
Wallpaper extension not running, Config screen not opening, Missing .json file

### ISSUE THREAD

**Issue by digitallybrushed** [TobiZog/cinnamon-dynamic-wallpaper#26]
Installed the Dynamic Wallpaper extension through the Cinnamon extension manager, and it will not work. It shows up in my extensions manager, but doesn't do anything. Wallpaper does not change from what I've manually set as my background wallpaper. Clicking on the settings button does nothing.

Tried restarting, and deactivating and reactivating, but that does not fix the problem.
Tried downloading the file and installing manually. Same result. Nothing happens.
Tried running the command in terminal:
`python3 .local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/src/main.py`

Here is the output:
`Traceback (most recent call last):
  File "/home/drakkan/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/src/main.py", line 10, in <module>
    main = Main_Window()
  File "/home/drakkan/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/src/view/main_window.py", line 33, in __init__
    self.view_model = Main_View_Model()
  File "/home/drakkan/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/src/model/main_view_model.py", line 40, in __init__
    self.cinnamon_prefs = Cinnamon_Pref_Handler()
  File "/home/drakkan/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/src/service/cinnamon_pref_handler.py", line 11, in __init__
    self.load_preferences()
  File "/home/drakkan/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/src/service/cinnamon_pref_handler.py", line 32, in load_preferences
    with open(self.pref_location, "r") as pref_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/drakkan/.config/cinnamon/spices/cinnamon-dynamic-wallpaper@TobiZog/cinnamon-dynamic-wallpaper@TobiZog.json'`

Checked for the folder "/home/drakkan/.config/cinnamon/spices/cinnamon-dynamic-wallpaper@TobiZog/" and sure enough, it does not exist. Tried to manually create it, but do not know where to get the "cinnamon-dynamic-wallpaper@TobiZog.json" file from, or how to generate it.

Could this be an issue with the ".config" folder since it doesn't have the "cinnamon/spices" folder in it, or is it a Cinnamon issue? 

Would love to get the dynamic wallpaper back up and running on my computer.

My system:
Linux Mint 21
Linux Kernel 5.15.0-118-generic
Cinnamon 5.4.12

**Comment by digitallybrushed** [comment]
Okay, I think I figured it out.
I think it's because I am using Linux Mint 21, and my version of Cinnamon is 5.4.12.
Apparently my version of Cinnamon places the spices and config files in the "/home/drakkan/.cinnamon/configs/" folder instead of "/home/drakkan/.config/cinnamon/spices/".

I copied the "cinnamon-dynamic-wallpaper@TobiZog.json" from the "/home/drakkan/.cinnamon/configs/cinnamon-dynamic-wallpaper@TobiZog" into the folder "/home/drakkan/.config/cinnamon/spices/cinnamon-dynamic-wallpaper@TobiZog", and then ran the command `python3 .local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/src/main.py` and it appears to be working now.

I also tried clicking on the settings button in the extensions manager, and it brings up the preferences from there now too.

This seems to have it functioning for now since it has access to the JSON file now, but I don't think it will be able to get updated if the extension gets updated since I copied the necessary file into a the spot the script is looking for it, but the system will place the extension files in a folder different from where the script looks for it because of my version of Cinnamon.
ie: `/home/drakkan/.cinnamon/configs/cinnamon-dynamic-wallpaper@TobiZog` instead of `/home/drakkan/.config/cinnamon/spices/cinnamon-dynamic-wallpaper@TobiZog`
